CREATE TABLE users
(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  username TEXT UNIQUE NOT NULL, 
  password TEXT NOT NULL,
  is_admin BOOL DEFAULT false NOT NULL 
);

CREATE TABLE residents
(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  balance NUMERIC NOT NULL DEFAULT 0.00,
  user_id INT REFERENCES users(id) ON DELETE CASCADE UNIQUE NOT NULL
);

CREATE TABLE units
(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  unit_num INT UNIQUE NOT NULL,
  resident_id INT REFERENCES residents(id) ON DELETE CASCADE UNIQUE
);

CREATE TABLE payments
(
  id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
  payment NUMERIC NOT NULL,
  end_balance NUMERIC NOT NULL,
  notes TEXT,
  trans_date TIMESTAMPTZ DEFAULT now() NOT NULL,
  user_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL
);

CREATE TABLE user_payments
(
  user_id INT REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  payment_id INT REFERENCES payments(id) ON DELETE CASCADE NOT NULL
);

INSERT INTO units (unit_num) values (2011), (2013), (2015), (2017), (2019);